### ISSUE TITLE
issue #1 still unfixed

### ISSUE THREAD

**Issue by Kikithecat12345** [MrMelon54/extra_armor_info#3]
issue #1 is still a problem and im still angery

im running a AMD K6-2 and 4MB ram with a sound blaster pro 2.0 and 1.44mb 3.5" floppy drive.

**Comment by mrmelon54** [comment]
does java even run on that?

maybe version 0.0.0.0.1.2 but probably not 1.8

**Comment by Kikithecat12345** [comment]
WONTFIX????? IM MAD IM FUMING IM STOMPING!!!
